apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: concert-nginx
  name: concert-nginx
  namespace: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: concert-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: concert-nginx
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: concert-nginx
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: concert-nginx
      containers:
      - name: concert-nginx
        image: 381492217459.dkr.ecr.ap-northeast-2.amazonaws.com/concert-nginx:v2.0
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 30
        resources:
          requests:
            memory: 100Mi
            cpu: 60m
          limits:
            memory: 100Mi
            cpu: 60m
