apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/concert-nginx/deploy.yaml
  - base/concert-nginx/service.yaml
  - base/concert-nginx/hpa.yaml
  - base/concert-tomcat/deploy.yaml
  - base/concert-tomcat/service.yaml
  - base/concert-tomcat/hpa.yaml
  - base/login-nginx/deploy.yaml
  - base/login-nginx/service.yaml
  - base/login-nginx/hpa.yaml
  - base/login-tomcat/deploy.yaml
  - base/login-tomcat/service.yaml
  - base/login-tomcat/hpa.yaml
  - base/root-nginx/deploy.yaml
  - base/root-nginx/service.yaml
  - base/root-nginx/hpa.yaml
  - base/root-tomcat/deploy.yaml
  - base/root-tomcat/service.yaml
  - base/root-tomcat/hpa.yaml
  - base/stg-ingress.yaml

patches:
  - path: overlays/stg/patch.yaml
    target:
      kind: Deployment


