apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/concert-nginx/deploy.yaml
  - base/concert-nginx/service.yaml
  - base/concert-nginx/hpa.yaml
  - base/concert-tomcat/deploy.yaml
  - base/concert-tomcat/service.yaml
  - base/concert-tomcat/hpa.yaml
  - base/login-nginx/deploy.yaml
  - base/login-nginx/service.yaml
  - base/login-nginx/hpa.yaml
  - base/login-tomcat/deploy.yaml
  - base/login-tomcat/service.yaml
  - base/login-tomcat/hpa.yaml
  - base/root-nginx/deploy.yaml
  - base/root-nginx/service.yaml
  - base/root-nginx/hpa.yaml
  - base/root-tomcat/deploy.yaml
  - base/root-tomcat/service.yaml
  - base/root-tomcat/hpa.yaml
  - base/stg-ingress.yaml

patches:
  - path: overlays/stg/concert-nginx-patch.yaml
    target:
      kind: Deployment
      name: concert-nginx
  - path: overlays/stg/concert-tomcat-patch.yaml
    target:
      kind: Deployment
      name: concert-tomcat
  - path: overlays/stg/login-nginx-patch.yaml
    target:
      kind: Deployment
      name: login-nginx
  - path: overlays/stg/login-tomcat-patch.yaml
    target:
      kind: Deployment
      name: login-tomcat
  - path: overlays/stg/root-nginx-patch.yaml
    target:
      kind: Deployment
      name: root-nginx
  - path: overlays/stg/root-tomcat-patch.yaml
    target:
      kind: Deployment
      name: root-tomcat


